package miniEnglish;

public enum MENonterminal {

    SENTENCE, NOUN_PHRASE, ABS_NOUN_PHRASE, CONC_NOUN_PHRASE,
    CNPA, NOMINAL, REL_CLAUSE, PREP_PHRASE, VERB_PHRASE, VPA, VPB,
    THAT, ART, ADJ, NOUN, PERS_PRON, REL_PRON, PREP, ADV, VERB 
}
